/*
Yang Ming Track and Trace API

API specifications for the Track and Trace interface standard

API version: DCSA Standard
Contact: itcs@yangming.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package yangming

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TransportEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransportEvent{}

// TransportEvent The transport event entity is a specialization of the event entity to support specification of data that only applies to a transport event.
type TransportEvent struct {
	// The unique identifier for the event (the message - not the source).<br>NB: This field should be considered Metadata<br>
	EventID *string `json:"eventID,omitempty"`
	// The timestamp of when the event was created.<br>NB: This field should be considered Metadata<br>
	EventCreatedDateTime time.Time `json:"eventCreatedDateTime"`
	// The Event Type of the object - to be used as a discriminator. <br>NB: This field should be considered Metadata<br><br>Enum:<br>[ TRANSPORT ]<br>
	EventType string `json:"eventType"`
	// Code for the event classifier can be   - ACT (Actual)    - PLN (Planned)    - EST (Estimated)  Enum:<br>[ ACT, PLN, EST ]
	EventClassifierCode string `json:"eventClassifierCode"`
	// The local date and time, where the event took place or when the event will take place, in ISO 8601 format.
	EventDateTime time.Time `json:"eventDateTime"`
	// Identifier for type of Transport event   - ARRI (Arrived)   - DEPA (Departed)  More details can be found on GitHub<br><br>Enum:<br>[ ARRI, DEPA ]
	TransportEventTypeCode string `json:"transportEventTypeCode"`
	// <small>maxLength: 3</small><br>Reason code for the delay. The SMDG-Delay-Reason-Codes are used for this attribute. The code list can be found at http://www.smdg.org/smdg-code-lists/
	DelayReasonCode *string `json:"delayReasonCode,omitempty"`
	// <small>maxLength: 250</small><br>Free text information provided by the vessel operator regarding the reasons for the change in schedule and/or plans to mitigate schedule slippage.
	ChangeRemark       *string              `json:"changeRemark,omitempty"`
	TransportCall      TransportCall        `json:"transportCall"`
	DocumentReferences []DocumentReferences `json:"documentReferences,omitempty"`
	References         []References         `json:"references,omitempty"`
}

type _TransportEvent TransportEvent

// NewTransportEvent instantiates a new TransportEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportEvent(eventCreatedDateTime time.Time, eventType string, eventClassifierCode string, eventDateTime time.Time, transportEventTypeCode string, transportCall TransportCall) *TransportEvent {
	this := TransportEvent{}
	this.EventCreatedDateTime = eventCreatedDateTime
	this.EventType = eventType
	this.EventClassifierCode = eventClassifierCode
	this.EventDateTime = eventDateTime
	this.TransportEventTypeCode = transportEventTypeCode
	this.TransportCall = transportCall
	return &this
}

// NewTransportEventWithDefaults instantiates a new TransportEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportEventWithDefaults() *TransportEvent {
	this := TransportEvent{}
	return &this
}

// GetEventID returns the EventID field value if set, zero value otherwise.
func (o *TransportEvent) GetEventID() string {
	if o == nil || IsNil(o.EventID) {
		var ret string
		return ret
	}
	return *o.EventID
}

// GetEventIDOk returns a tuple with the EventID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetEventIDOk() (*string, bool) {
	if o == nil || IsNil(o.EventID) {
		return nil, false
	}
	return o.EventID, true
}

// HasEventID returns a boolean if a field has been set.
func (o *TransportEvent) HasEventID() bool {
	if o != nil && !IsNil(o.EventID) {
		return true
	}

	return false
}

// SetEventID gets a reference to the given string and assigns it to the EventID field.
func (o *TransportEvent) SetEventID(v string) {
	o.EventID = &v
}

// GetEventCreatedDateTime returns the EventCreatedDateTime field value
func (o *TransportEvent) GetEventCreatedDateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EventCreatedDateTime
}

// GetEventCreatedDateTimeOk returns a tuple with the EventCreatedDateTime field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetEventCreatedDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventCreatedDateTime, true
}

// SetEventCreatedDateTime sets field value
func (o *TransportEvent) SetEventCreatedDateTime(v time.Time) {
	o.EventCreatedDateTime = v
}

// GetEventType returns the EventType field value
func (o *TransportEvent) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *TransportEvent) SetEventType(v string) {
	o.EventType = v
}

// GetEventClassifierCode returns the EventClassifierCode field value
func (o *TransportEvent) GetEventClassifierCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventClassifierCode
}

// GetEventClassifierCodeOk returns a tuple with the EventClassifierCode field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetEventClassifierCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventClassifierCode, true
}

// SetEventClassifierCode sets field value
func (o *TransportEvent) SetEventClassifierCode(v string) {
	o.EventClassifierCode = v
}

// GetEventDateTime returns the EventDateTime field value
func (o *TransportEvent) GetEventDateTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EventDateTime
}

// GetEventDateTimeOk returns a tuple with the EventDateTime field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetEventDateTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventDateTime, true
}

// SetEventDateTime sets field value
func (o *TransportEvent) SetEventDateTime(v time.Time) {
	o.EventDateTime = v
}

// GetTransportEventTypeCode returns the TransportEventTypeCode field value
func (o *TransportEvent) GetTransportEventTypeCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportEventTypeCode
}

// GetTransportEventTypeCodeOk returns a tuple with the TransportEventTypeCode field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetTransportEventTypeCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportEventTypeCode, true
}

// SetTransportEventTypeCode sets field value
func (o *TransportEvent) SetTransportEventTypeCode(v string) {
	o.TransportEventTypeCode = v
}

// GetDelayReasonCode returns the DelayReasonCode field value if set, zero value otherwise.
func (o *TransportEvent) GetDelayReasonCode() string {
	if o == nil || IsNil(o.DelayReasonCode) {
		var ret string
		return ret
	}
	return *o.DelayReasonCode
}

// GetDelayReasonCodeOk returns a tuple with the DelayReasonCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetDelayReasonCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DelayReasonCode) {
		return nil, false
	}
	return o.DelayReasonCode, true
}

// HasDelayReasonCode returns a boolean if a field has been set.
func (o *TransportEvent) HasDelayReasonCode() bool {
	if o != nil && !IsNil(o.DelayReasonCode) {
		return true
	}

	return false
}

// SetDelayReasonCode gets a reference to the given string and assigns it to the DelayReasonCode field.
func (o *TransportEvent) SetDelayReasonCode(v string) {
	o.DelayReasonCode = &v
}

// GetChangeRemark returns the ChangeRemark field value if set, zero value otherwise.
func (o *TransportEvent) GetChangeRemark() string {
	if o == nil || IsNil(o.ChangeRemark) {
		var ret string
		return ret
	}
	return *o.ChangeRemark
}

// GetChangeRemarkOk returns a tuple with the ChangeRemark field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetChangeRemarkOk() (*string, bool) {
	if o == nil || IsNil(o.ChangeRemark) {
		return nil, false
	}
	return o.ChangeRemark, true
}

// HasChangeRemark returns a boolean if a field has been set.
func (o *TransportEvent) HasChangeRemark() bool {
	if o != nil && !IsNil(o.ChangeRemark) {
		return true
	}

	return false
}

// SetChangeRemark gets a reference to the given string and assigns it to the ChangeRemark field.
func (o *TransportEvent) SetChangeRemark(v string) {
	o.ChangeRemark = &v
}

// GetTransportCall returns the TransportCall field value
func (o *TransportEvent) GetTransportCall() TransportCall {
	if o == nil {
		var ret TransportCall
		return ret
	}

	return o.TransportCall
}

// GetTransportCallOk returns a tuple with the TransportCall field value
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetTransportCallOk() (*TransportCall, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransportCall, true
}

// SetTransportCall sets field value
func (o *TransportEvent) SetTransportCall(v TransportCall) {
	o.TransportCall = v
}

// GetDocumentReferences returns the DocumentReferences field value if set, zero value otherwise.
func (o *TransportEvent) GetDocumentReferences() []DocumentReferences {
	if o == nil || IsNil(o.DocumentReferences) {
		var ret []DocumentReferences
		return ret
	}
	return o.DocumentReferences
}

// GetDocumentReferencesOk returns a tuple with the DocumentReferences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetDocumentReferencesOk() ([]DocumentReferences, bool) {
	if o == nil || IsNil(o.DocumentReferences) {
		return nil, false
	}
	return o.DocumentReferences, true
}

// HasDocumentReferences returns a boolean if a field has been set.
func (o *TransportEvent) HasDocumentReferences() bool {
	if o != nil && !IsNil(o.DocumentReferences) {
		return true
	}

	return false
}

// SetDocumentReferences gets a reference to the given []DocumentReferences and assigns it to the DocumentReferences field.
func (o *TransportEvent) SetDocumentReferences(v []DocumentReferences) {
	o.DocumentReferences = v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *TransportEvent) GetReferences() []References {
	if o == nil || IsNil(o.References) {
		var ret []References
		return ret
	}
	return o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEvent) GetReferencesOk() ([]References, bool) {
	if o == nil || IsNil(o.References) {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *TransportEvent) HasReferences() bool {
	if o != nil && !IsNil(o.References) {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []References and assigns it to the References field.
func (o *TransportEvent) SetReferences(v []References) {
	o.References = v
}

func (o TransportEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransportEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventID) {
		toSerialize["eventID"] = o.EventID
	}
	toSerialize["eventCreatedDateTime"] = o.EventCreatedDateTime
	toSerialize["eventType"] = o.EventType
	toSerialize["eventClassifierCode"] = o.EventClassifierCode
	toSerialize["eventDateTime"] = o.EventDateTime
	toSerialize["transportEventTypeCode"] = o.TransportEventTypeCode
	if !IsNil(o.DelayReasonCode) {
		toSerialize["delayReasonCode"] = o.DelayReasonCode
	}
	if !IsNil(o.ChangeRemark) {
		toSerialize["changeRemark"] = o.ChangeRemark
	}
	toSerialize["transportCall"] = o.TransportCall
	if !IsNil(o.DocumentReferences) {
		toSerialize["documentReferences"] = o.DocumentReferences
	}
	if !IsNil(o.References) {
		toSerialize["references"] = o.References
	}
	return toSerialize, nil
}

func (o *TransportEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventCreatedDateTime",
		"eventType",
		"eventClassifierCode",
		"eventDateTime",
		"transportEventTypeCode",
		"transportCall",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransportEvent := _TransportEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransportEvent)

	if err != nil {
		return err
	}

	*o = TransportEvent(varTransportEvent)

	return err
}

type NullableTransportEvent struct {
	value *TransportEvent
	isSet bool
}

func (v NullableTransportEvent) Get() *TransportEvent {
	return v.value
}

func (v *NullableTransportEvent) Set(val *TransportEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportEvent(val *TransportEvent) *NullableTransportEvent {
	return &NullableTransportEvent{value: val, isSet: true}
}

func (v NullableTransportEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
